version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:22.21.1
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: show version
          command: node ./build/index.js -v

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
