version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:22.21.1
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install -g npm@latest
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
